export function setChangedElement(elem: HTMLElement): void;
export function resetChangedElement(elem: any): void;
export function fromSchema(source: any, schema: any): {};
export function groupSettingsOnAdd(elementId: any, listener: any): void;
export function getData(forms: any, options: any): {
    set: {};
    del: any[];
};
export function getDataForElement(element: any): any;
export function setInputValue(input: any, value: any): void;
export function setSpanValue(span: any, value: any): void;
export function setSelectValue(select: any, value: any): void;
export function setOriginalsFromValuesForNode(node: any, elems: any): void;
export function setOriginalsFromValues(elems: any): void;
export function initSelect(select: any, values: any): void;
export function addEnumerables(name: any, enumerables: any): void;
export function addSimpleEnumerables(name: any, prettyName: any, count: any): void;
export function initGenericKeyValueElement(key: any, value: any): void;
export function idForTemplateContainer(container: any): any;
export function onElementChange(event: any): void;
export function listenVariables(key: any, func: any): void;
export function variableListeners(listeners: any): void;
export function updateKeyValue(key: any, value: any): void;
export function askSaveSettings(ask: any): any;
export function updateVariables(kvs: any): void;
export function init(): void;
